#################################################################
#              WARNING: Auto-Generated File
#  This file was generated by a tool(py/pyis-torch/code_gen.py)
#  Any changes made to it will be overwritten when regenerated
#################################################################

